ALTER TABLE "ihale_belgeleri"
ADD COLUMN "durum" TEXT NOT NULL DEFAULT 'AKTIF',
ADD COLUMN "silinmeTarihi" TIMESTAMP(3),
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "ihale_belgeleri" ALTER COLUMN "updatedAt" DROP DEFAULT;
